version: 2
 
models:
  - name: dim_customer
    description: Измерение "клиент". Грануляция 1 строка = 1 клиент.
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
 
  - name: dim_account
    description: Измерение "счёт". Грануляция 1 строка = 1 счёт.
    columns:
      - name: account_id
        tests:
          - unique
          - not_null
 
  - name: dim_merchant
    description: Измерение "мерчант". Грануляция 1 строка = 1 мерчант.
    columns:
      - name: merchant_id
        tests:
          - unique
          - not_null
 
  - name: fct_transaction
    description: Факт "транзакция". Грануляция 1 строка = 1 транзакция.
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
