version: 2
 
models:
  - name: mart_daily_transactions
    description: Ежедневный объём и сумма транзакций. Грануляция 1 строка = 1 день.
    columns:
      - name: date
        tests:
          - unique
          - not_null
 
  - name: mart_customer_activity
    description: >
      Сводка активности по каждому клиенту. Включает клиентов без единой
      транзакции (transaction_count = 0). Грануляция 1 строка = 1 клиент.
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
 
  - name: mart_merchant_performance
    description: >
      Сводка эффективности по каждому мерчанту. Включает мерчантов без
      единой транзакции. Грануляция 1 строка = 1 мерчант.
    columns:
      - name: merchant_id
        tests:
          - unique
          - not_null
